/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Arjuna
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MnuIngreso = new javax.swing.JMenuItem();
        MnuSalida = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MnuBD = new javax.swing.JMenuItem();
        MnuBuscar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MnuPDF = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PnEscritorioLayout = new javax.swing.GroupLayout(PnEscritorio);
        PnEscritorio.setLayout(PnEscritorioLayout);
        PnEscritorioLayout.setHorizontalGroup(
            PnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        PnEscritorioLayout.setVerticalGroup(
            PnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EscudoUD.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro");

        MnuIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modo-retrato.png"))); // NOI18N
        MnuIngreso.setText("Ingreso");
        jMenu2.add(MnuIngreso);

        MnuSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retrato(1).png"))); // NOI18N
        MnuSalida.setText("Salida");
        jMenu2.add(MnuSalida);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");

        MnuBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/base-de-datos.png"))); // NOI18N
        MnuBD.setText("Base de Datos");
        jMenu3.add(MnuBD);

        MnuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        MnuBuscar.setText("Buscar Ingreso");
        jMenu3.add(MnuBuscar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Generar");

        MnuPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-pdf.png"))); // NOI18N
        MnuPDF.setText("PDF");
        jMenu4.add(MnuPDF);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");

        MnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        MnuSalir.setText("Salir");
        jMenu5.add(MnuSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuBD;
    private javax.swing.JMenuItem MnuBuscar;
    private javax.swing.JMenuItem MnuIngreso;
    private javax.swing.JMenuItem MnuPDF;
    private javax.swing.JMenuItem MnuSalida;
    private javax.swing.JMenuItem MnuSalir;
    private javax.swing.JDesktopPane PnEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMnuBD() {
        return MnuBD;
    }

    public void setMnuBD(JMenuItem MnuBD) {
        this.MnuBD = MnuBD;
    }

    public JMenuItem getMnuBuscar() {
        return MnuBuscar;
    }

    public void setMnuBuscar(JMenuItem MnuBuscar) {
        this.MnuBuscar = MnuBuscar;
    }

    public JMenuItem getMnuIngreso() {
        return MnuIngreso;
    }

    public void setMnuIngreso(JMenuItem MnuIngreso) {
        this.MnuIngreso = MnuIngreso;
    }

    public JMenuItem getMnuPDF() {
        return MnuPDF;
    }

    public void setMnuPDF(JMenuItem MnuPDF) {
        this.MnuPDF = MnuPDF;
    }

    public JMenuItem getMnuSalida() {
        return MnuSalida;
    }

    public void setMnuSalida(JMenuItem MnuSalida) {
        this.MnuSalida = MnuSalida;
    }

    public JMenuItem getMnuSalir() {
        return MnuSalir;
    }

    public void setMnuSalir(JMenuItem MnuSalir) {
        this.MnuSalir = MnuSalir;
    }

    public JDesktopPane getPnEscritorio() {
        return PnEscritorio;
    }

    public void setPnEscritorio(JDesktopPane PnEscritorio) {
        this.PnEscritorio = PnEscritorio;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenu getjMenu5() {
        return jMenu5;
    }

    public void setjMenu5(JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    
    
   

    
}
