/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Arjuna
 */
public class frmRegistrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar
     */
    public frmRegistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnRegistrar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CmbPuerta = new javax.swing.JComboBox<>();
        TxtNombre = new javax.swing.JTextField();
        CmbTipoDocumento = new javax.swing.JComboBox<>();
        TxtNDocumento = new javax.swing.JTextField();
        CmbIngreso = new javax.swing.JComboBox<>();
        CmbMotivo = new javax.swing.JComboBox<>();
        PnPlacas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TxtPlacas = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();

        setClosable(true);

        jLabel10.setText("Registro Ingreso UD-Tecnologica");

        jLabel11.setText("Puerta");

        jLabel12.setText("Nombre");

        jLabel13.setText("Tipo de documento");

        jLabel14.setText("# Documento");

        jLabel15.setText("Ingreso");

        jLabel16.setText("Motivo");

        CmbPuerta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        CmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula ciudadania", "Tarjeta de identidad", "Codigo institucional" }));

        CmbIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peatonal", "Automovil", "Moto", "Bicicleta" }));

        CmbMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Administrativo", "Trabajador", "Visitante" }));

        jLabel17.setText("Placas");

        javax.swing.GroupLayout PnPlacasLayout = new javax.swing.GroupLayout(PnPlacas);
        PnPlacas.setLayout(PnPlacasLayout);
        PnPlacasLayout.setHorizontalGroup(
            PnPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPlacasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(TxtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PnPlacasLayout.setVerticalGroup(
            PnPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPlacasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BtnRegistrar.setText("Registrar");

        javax.swing.GroupLayout PnRegistrarLayout = new javax.swing.GroupLayout(PnRegistrar);
        PnRegistrar.setLayout(PnRegistrarLayout);
        PnRegistrarLayout.setHorizontalGroup(
            PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnRegistrarLayout.createSequentialGroup()
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnRegistrarLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel10))
                    .addGroup(PnRegistrarLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(40, 40, 40)
                        .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CmbPuerta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtNombre)
                            .addComponent(CmbIngreso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtNDocumento)
                            .addComponent(CmbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PnRegistrarLayout.createSequentialGroup()
                                .addComponent(CmbMotivo, 0, 143, Short.MAX_VALUE)
                                .addGap(1, 1, 1))))
                    .addGroup(PnRegistrarLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(PnPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnRegistrarLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(BtnRegistrar)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        PnRegistrarLayout.setVerticalGroup(
            PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CmbPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtNDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CmbIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CmbMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRegistrar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CmbIngreso;
    private javax.swing.JComboBox<String> CmbMotivo;
    private javax.swing.JComboBox<String> CmbPuerta;
    private javax.swing.JComboBox<String> CmbTipoDocumento;
    private javax.swing.JPanel PnPlacas;
    private javax.swing.JPanel PnRegistrar;
    private javax.swing.JTextField TxtNDocumento;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPlacas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnRegistrar() {
        return BtnRegistrar;
    }

    public void setBtnRegistrar(JButton BtnRegistrar) {
        this.BtnRegistrar = BtnRegistrar;
    }

    public JComboBox<String> getCmbIngreso() {
        return CmbIngreso;
    }

    public void setCmbIngreso(JComboBox<String> CmbIngreso) {
        this.CmbIngreso = CmbIngreso;
    }

    public JComboBox<String> getCmbMotivo() {
        return CmbMotivo;
    }

    public void setCmbMotivo(JComboBox<String> CmbMotivo) {
        this.CmbMotivo = CmbMotivo;
    }

    public JComboBox<String> getCmbPuerta() {
        return CmbPuerta;
    }

    public void setCmbPuerta(JComboBox<String> CmbPuerta) {
        this.CmbPuerta = CmbPuerta;
    }

    public JComboBox<String> getCmbTipoDocumento() {
        return CmbTipoDocumento;
    }

    public void setCmbTipoDocumento(JComboBox<String> CmbTipoDocumento) {
        this.CmbTipoDocumento = CmbTipoDocumento;
    }

    public JPanel getPnPlacas() {
        return PnPlacas;
    }

    public void setPnPlacas(JPanel PnPlacas) {
        this.PnPlacas = PnPlacas;
    }

    public JPanel getPnRegistrar() {
        return PnRegistrar;
    }

    public void setPnRegistrar(JPanel PnRegistrar) {
        this.PnRegistrar = PnRegistrar;
    }

    public JTextField getTxtNDocumento() {
        return TxtNDocumento;
    }

    public void setTxtNDocumento(JTextField TxtNDocumento) {
        this.TxtNDocumento = TxtNDocumento;
    }

    public JTextField getTxtNombre() {
        return TxtNombre;
    }

    public void setTxtNombre(JTextField TxtNombre) {
        this.TxtNombre = TxtNombre;
    }

    public JTextField getTxtPlacas() {
        return TxtPlacas;
    }

    public void setTxtPlacas(JTextField TxtPlacas) {
        this.TxtPlacas = TxtPlacas;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    
    
    
}
